config/routes.rb
Nakama::Application.routes.draw do
    get "nakama/index"
    get "/about" => "nakama#about"

    get "/words/random" => "words#random"
    get "/kanji/random" => "kanjis#random"

    resources :users
    resources :sessions
    resources :photos
    resources :words
    resources :user_words
    resources :kanjis, :path => '/kanji'

    get "/capture" => "photos#new"
    get "/myimages" => "photos#index"

    get "/sample" => "photos#sample"
    
    post "kanji/find" => "kanji#find_character"

    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    get "/signup" => "users#new"

    get "/dictionary/:q" => "words#index"
    get "/dictionary/" => "words#index"
    get "/glossary" => "words#glossary"
    get "/glossary/:c" => "words#glossary", as: :glossary_search
    get "/search" => "words#search"
    get "/mywords" => "user_words#index"

    root 'nakama#index'

end

app/controllers/nakama_controller.rb
class NakamaController < ApplicationController
    def index
        @photo = Photo.new
    end

    def about
    end
end

app/helpers/nakama_helper.rb
module NakamaHelper
end

app/views/nakama/about.html.erb
<% content_for(:title, "About") %>
<% content_for(:description, "About the page and contributions") %>

<div class="row">
    <div class="col-md-6">
        <h1>About</h1>

        <p>Reading novels and other texts in Japanese can be hard, especially for students of Japanese, such as myself, that don't know every kanji. Nakama is an attempt to make looking up kanji slightly faster by using <abbr title="Optical Character Recognition" class="initialism">OCR</abbr>.</p>

        <h3>Special thanks <small>(in no special order)</small></h3>
        <ul>
            <li>The dictionary and Kanji data comes from Jim Breen's <%= link_to "WWWJDIC", "http://www.edrdg.org/jmdict/edict_doc.html" %> project.</li>
            <li>The <%= link_to "Tanaka Corpus", "http://www.edrdg.org/wiki/index.php/Tanaka_Corpus" %> was used for the sentence data.</li>
            <li>Kanji stroke order data from <%= link_to "KanjiVG", "http://kanjivg.tagaini.net/" %> was used for the kanji diagrams.</li>
            <li>All icons used come from <%= link_to "Font Awesome", "http://fontawesome.io" %> by Dave Gandy</li>
            <li><%= link_to "Bootstrap", "http://getbootstrap.com/" %> was used for the design.</li>
            <li>OCR is done with <%= link_to "Google Tesseract", "https://code.google.com/p/tesseract-ocr/" %>.</li>
        </ul>

        <p>This application was created by <%= link_to "Andreas Argelius", "http://argeli.us" %>. The <%= link_to "source code", "https://bitbucket.org/argelius/nakama" %> is released under the <%= link_to "MIT license.", "http://opensource.org/licenses/MIT" %></p>
    </div>
</div>
<hr>
<footer>
<span class="text-muted">&copy; 2014 Andreas Argelius</span>
</footer>

app/views/nakama/index.html.erb
<% content_for(:title, "Japanese dictionary") %>

<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-8">
                <h3>Dictionary search</h3>
                <%= render "words/search" %>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <h3>Find words in images</h3>
                <p>You can upload scanned images or photographs from your mobile phone. Swipe the words or characters that you want to know the meaning of.</p>
                <p>
                <%= form_for @photo, :html => { :multipart => true } do |f| %>
                    <%= f.file_field :file, :accept => "image/*", :class => "form-control", :class => "hide" %>
                    <%= button_tag(:class => "btn btn-default", :id => "capture") do %>
                        <i class="fa fa-camera"></i> Capture from camera
                    <% end %>
                    <%= button_tag(:class => "btn btn-default", :id => "upload") do %>
                        <i class="fa fa-upload"></i> Upload from disk
                    <% end %> 
                <% end %>
                </p>
                <p>You can try it out on a <%= link_to "sample image", sample_path %>.</p>
            </div>
        </div>
    </div>
    <div class="well col-md-4">
        <h3>About <%= title %></h3>

        <p><%= title %> is a Japanese dictionary application. It is designed to be usable both on a desktop computer as well as on a mobile device.</p>

        <p>This is work in progress and should be considered an alpha version. Don't be alarmed if things break randomly. Please send bug reports and suggestions to <%= mail_to("andreas.argelius@gmail.com", "Andreas Argelius") %>.

        <p>Features to be (but not yet) implemented:</p>

        <ul>
            <li>Radical search</li>
            <li>Handwriting recognition</li>
        </ul>
    </div>
</div>
<hr>
<footer>
<span class="text-muted">&copy; 2014 Andreas Argelius</span>
</footer>