config/routes.rb
Nakama::Application.routes.draw do
    get "nakama/index"
    get "/about" => "nakama#about"

    get "/words/random" => "words#random"
    get "/kanji/random" => "kanjis#random"

    resources :users
    resources :sessions
    resources :photos
    resources :words
    resources :user_words
    resources :kanjis, :path => '/kanji'

    get "/capture" => "photos#new"
    get "/myimages" => "photos#index"

    get "/sample" => "photos#sample"
    
    post "kanji/find" => "kanji#find_character"

    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    get "/signup" => "users#new"

    get "/dictionary/:q" => "words#index"
    get "/dictionary/" => "words#index"
    get "/glossary" => "words#glossary"
    get "/glossary/:c" => "words#glossary", as: :glossary_search
    get "/search" => "words#search"
    get "/mywords" => "user_words#index"

    root 'nakama#index'

end

app/models/word.rb
# encoding: utf-8

class Word < ActiveRecord::Base
    def to_param
        @words = Word.where(:kanji => kanji)

        if @words.count() == 1
            kanji
        else
            "#{kanji}-#{id}"
        end
    end
    
    self.per_page = 10
    
    has_many :definitions

    has_many :user_words
    has_many :users, :through => :user_words

    validates_presence_of :kanji, :on => :create

    def self.search(q)
        result = joins(:definitions)

        q.strip!
        if q.length > 0
            q.split(/[ 　]+/).each do |w|
                if w.include? "*"
                    patt = w.gsub "*", "%"
                else
                    patt = "%#{w}%"
                end
            
                if w.ascii_only?
                    result = result.where("LOWER(definitions.text) LIKE LOWER(?)", "%#{w}%")
                else
                    result = result.where("kanji LIKE ? or kana LIKE ?", patt, patt)
                end
            end
        end

        result.group("words.id").order("common DESC, length(kanji), kana")
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
    def index
        if params[:q].nil?
            @words = nil
        else
            @words = Word.search(params[:q]).
                paginate(:page => params[:page])
        end
    end

    def glossary
        c = params[:c]

        @words = Word.where("kana LIKE ?", "#{c}%")

        idx = if c.nil? then 1 else c.length+1 end
        @characters = @words.
            select("SUBSTR(kana, #{idx}, 1) AS character").
            group("character").
            order("character ASC")

        @words = @words.
            where("LENGTH(?) > 0", c).
            includes(:definitions).
            paginate(:page => params[:page])
    end

    def show
        if params[:id].include? '-'
            @word = Word.find(params[:id].split("-")[1])
        elsif params[:id] =~ /^[0-9]+$/
            @word = Word.find(params[:id])
        else
            @word = Word.where(:kanji => params[:id]).first
        end

        @kanjis = Kanji.where("character in (?)", @word.kanji.scan(/./))
        @sentences = Sentence.where("japanese_raw LIKE ?", "%#{@word.kanji}%").
            order("LENGTH(japanese) ASC").paginate(:page => params[:page])
    end

    def search
        @word = Word.search(params[:q] || "").first

        if params[:q].nil? or not @word
            render json: { :result => "error", :message => "no result" }, status: :not_found
        else
            render json: {
                :result => "success",
                :word => @word,
                :definitions => @word.definitions,
                :link => view_context.link_to(@word.kanji, @word)
            }
        end
    end

    def random
        @word = Word.
            where(:common => true).
            includes(:definitions).
            order("RANDOM()").
            first

        render "random"
    end
end

app/helpers/words_helper.rb
# encoding: UTF-8

module WordsHelper
    def verb_forms(word)
        forms = [word]

        if word =~ /[うるつすぐくぬむ]$/
            case word[-1]
            when 'う'
                forms << word.sub(/う$/, "い")
                forms << word.sub(/う$/, "って")
                forms << word.sub(/う$/, "った")
                forms << word.sub(/う$/, "わ")
                forms << word.sub(/う$/, "お")
                forms << word.sub(/う$/, "え")
            when 'る'
                forms << word.sub(/る$/, "り")
                forms << word.sub(/る$/, "ら")
                forms << word.sub(/る$/, "って")
                forms << word.sub(/る$/, "た")
                forms << word.sub(/る$/, "て")
                forms << word.sub(/る$/, "ろ")
                forms << word.sub(/る$/, "よ")
                forms << word.sub(/る$/, "れ")
                forms << word.sub(/る$/, "")
            when 'つ'
                forms << word.sub(/つ$/, "ち")
                forms << word.sub(/つ$/, "た")
                forms << word.sub(/つ$/, "った")
                forms << word.sub(/つ$/, "って")
                forms << word.sub(/つ$/, "と")
                forms << word.sub(/つ$/, "て")
            when 'す'
                forms << word.sub(/す$/, "して")
                forms << word.sub(/す$/, "さ")
                forms << word.sub(/す$/, "した")
                forms << word.sub(/す$/, "し")
                forms << word.sub(/す$/, "そ")
                forms << word.sub(/す$/, "せ")
            when 'ぐ'
                forms << word.sub(/ぐ$/, "いだ")
                forms << word.sub(/ぐ$/, "いで")
                forms << word.sub(/ぐ$/, "ぎ")
                forms << word.sub(/ぐ$/, "が")
                forms << word.sub(/ぐ$/, "ご")
                forms << word.sub(/ぐ$/, "げ")
            when 'く'
                forms << word.sub(/く$/, "いた")
                forms << word.sub(/く$/, "いて")
                forms << word.sub(/く$/, "き")
                forms << word.sub(/く$/, "か")
                forms << word.sub(/く$/, "こ")
                forms << word.sub(/く$/, "け")
            when 'ぬ'
                forms << word.sub(/ぬ$/, "んだ")
                forms << word.sub(/ぬ$/, "んで")
                forms << word.sub(/ぬ$/, "に")
                forms << word.sub(/ぬ$/, "な")
                forms << word.sub(/ぬ$/, "の")
                forms << word.sub(/ぬ$/, "ね")
            when 'む'
                forms << word.sub(/む$/, "んだ")
                forms << word.sub(/む$/, "んで")
                forms << word.sub(/む$/, "み")
                forms << word.sub(/む$/, "ま")
                forms << word.sub(/む$/, "も")
                forms << word.sub(/む$/, "め")
            end

            
        end

        return forms
    end
end

app/views/words/_search.html.erb
<p>Input kana, kanji or English words in the box below.</p>
<small><p class="text-muted">Use '*' as a wildcard, e.g. to search for all words starting with "本", type: "本*". Switch input mode by clicking the icon.</p></small>
<%= form_tag dictionary_path, :method => 'get', :class => "form-inline" do %>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group">
                    <span id="switch-input-mode" class="input-group-addon">あ</span>
                    <%= search_field_tag :q, params[:q], :class => "form-control" %>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <%= button_tag :class => "btn btn-default" do %>
                <i class="fa fa-search"></i>&nbsp; Search
            <% end %>
        </div>
    </div>
<% end %>

app/views/words/glossary.html.erb
<h3>Glossary</h3>

<% if params[:c].nil? %>
    <% content_for(:title, "Glossary") %>
    <% content_for(:description, "Japanese glossary. Find words by starting characters.") %>
<% else %>
    <% content_for(:title, "Glossary - #{params[:c]}") %>
    <% if params[:page] 
        content_for(:title, " - Page #{params[:page]}")
    end %>
    <% content_for(:description, "Japanese glossary. Find words starting with #{params[:c]}") %>
    <ol class="breadcrumb">
        <li><%= link_to "Home", glossary_path %></li>
        <% current = "" %>
        <% params[:c].scan(/./)[0..-2].each do |c| %>
            <% current += c %>
            <li><%= link_to current, glossary_search_path(:c => current) %></li>
        <% end %>
        <li class="active"><%= params[:c] %></li>
    </ol>
<% end %>

<div id="glossary-index">
    <% @characters.each do |c| %>
        <%= link_to c.character, glossary_search_path(:c => "#{params[:c]}#{c.character}") %>
    <% end %>
</div>

<% if not @words.nil? and @words.length > 0 %>
    <hr>
    <h4>Words</h4>
    <% @words.each do |w| %>
        <%= link_to w.kanji, w %> <% if w.kana %>&nbsp;<span class="text-muted"><%= w.kana %></span><% end %>
        <% if w.common %>
            <span class="label label-default">common</span>
        <% end %>
        <small>
            <ol>
                <% w.definitions.each do |d| %>
                    <li><%= d.text %></li>
                <% end %>
            </ol>
        </small>
    <% end %>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= will_paginate @posts, :renderer => BootstrapPagination::Rails, :inner_window => 1, :outer_window => 0, :previous_label => "&laquo;", :next_label => "&raquo;" %>
        </div>
    </div>
<% end %>

app/views/words/index.html.erb
<% if params[:q].nil? %>
    <% content_for(:title, "Japanese dictionary search") %>
    <% content_for(:description, "Japanese dictionary search. Search for Japanese words and English definitions using hiragana, katakana, kanji or English.") %>
<% else %>
    <% content_for(:title, "Japanese dictionary search - #{params[:q]}") %>
    <% if params[:page] 
        content_for(:title, " - Page #{params[:page]}")
    end %>
    <% content_for(:description, "Japanese dictionary search results for #{params[:q]}. Find English definitions and example sentences.") %> 
<% end %>

<h3>Dictionary search</h3>
<%= render "words/search" %>
<% if params[:q] %>
    <% mark = params[:q].gsub("*", "").strip.split(/[ 　]+/).sort_by(&:length).reverse %>
    <hr>
    <h4>Words for "<%= highlight(params[:q], mark) %>"</h4>
    <p class="text-muted"><small><%= page_entries_info @words, :model => "entry" %></small></p>
    <% @words.each do |w| %>
        <h3>
            <%= link_to w do %><%= highlight(w.kanji, mark) %><% end %>
            <% if w.kana %>&nbsp;
                <small><%= highlight(w.kana, mark) %></small>
            <% end %>
        </h3>
        <% if w.common %>
            <small class="text-success">Common word</small>
        <% end %>
        <ol>
            <% w.definitions.each do |d| %>
                <li><%= highlight(d.text, mark) %></li>
            <% end %>
        </ol>
    <% end %>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= will_paginate @posts, :renderer => BootstrapPagination::Rails, :inner_window => 1, :outer_window => 0, :previous_label => "&laquo;", :next_label => "&raquo;" %>
        </div>
    </div>
<% end %>

app/views/words/random.json.erb
{
    "word": <%= raw @word.to_json(:include => :definitions) %>,
    "link": "<%= url_for(@word) %>"
}

app/views/words/show.html.erb
<% content_for(:title, "Dictionary - #{@word.kanji}") %>
<% content_for(:description, "Japanese dictionary entry for #{@word.kanji}. Find English definitions for this word and example sentences.") %>

<div class="row">
    <div class="col-md-6">
        <h2>
            <%= @word.kanji %>
            <% if @word.kana %>
                <span class="text-muted">
                <%= @word.kana %>
            </span>
        <% end %>
            <% if @word.common %>
                <small><span class="label label-default">common</span></small>
        <% end %>
        </h2>
        <% if current_user %>
            <%= link_to "Add to my words", user_words_path(:id => @word.id), :method => :post, :id => 0 %>
    <% end %>
        <hr>
        <h3>English definitions</h3>
        <ol>
            <% @word.definitions.each do |d| %>
                <li><%= d.text %></li>
        <% end %>
        </ol>
    </div>
    <div class="col-md-4 well">
        <h4>Kanji in this word</h4>
        <% if @kanjis.count > 0 %>
            <dl>
            <% @kanjis.each do |k| %>
                <dt><%= link_to k.character, k %></dt>
            <dd>&nbsp;<small><%= k.meanings.map(&:text).join(", ") %></small></dd>
        <% end %>
        </dl>
    <% else %>
            <p>There are no kanji in this word.</p>
    <% end %>
    </div>
</div>

<h3>Sentences</h3>
<% if @sentences.length > 0 %>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Japanese</th>
            <th>English</th>
        </tr>
    </thead>
    <tbody>
    <% @sentences.each do |s| %>
        <% 
                words = {}
        s.japanese_raw.split(" ").each do |w| 
            w =~ /([^{(\[~]*)/

            in_dictionary = in_sentence = $1

            if w =~ /\{(.*)\}/
                in_sentence = $1
            end

            if w =~ /\((.*)\)/
                kana = $1
            end
            words[in_sentence] = in_dictionary
        end

        words.keys.sort_by(&:length).reverse().each do |k|
            s.japanese.gsub!(/#{k}(?!<\/a>)/, link_to(k, dictionary_path(:q=>words[k])))
        end
    %>
    <tr>
            <td><%= highlight(s.japanese, verb_forms(@word.kanji)) %></td>
            <td><%= s.english %></td>
        </tr>
        </tbody>
    <% end %>
    </table>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= will_paginate @sentences, :renderer => BootstrapPagination::Rails, :inner_window => 1, :outer_window => 0, :previous_label => "&laquo;", :next_label => "&raquo;" %>
        </div>
    </div>
<% else %>
    <p>There are no example sentences for this word.</p>
<% end %>