config/routes.rb
Nakama::Application.routes.draw do
    get "nakama/index"
    get "/about" => "nakama#about"

    get "/words/random" => "words#random"
    get "/kanji/random" => "kanjis#random"

    resources :users
    resources :sessions
    resources :photos
    resources :words
    resources :user_words
    resources :kanjis, :path => '/kanji'

    get "/capture" => "photos#new"
    get "/myimages" => "photos#index"

    get "/sample" => "photos#sample"
    
    post "kanji/find" => "kanji#find_character"

    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    get "/signup" => "users#new"

    get "/dictionary/:q" => "words#index"
    get "/dictionary/" => "words#index"
    get "/glossary" => "words#glossary"
    get "/glossary/:c" => "words#glossary", as: :glossary_search
    get "/search" => "words#search"
    get "/mywords" => "user_words#index"

    root 'nakama#index'

end

app/models/definition.rb
class Definition < ActiveRecord::Base
    belongs_to :word

    validates :text, presence: true
end

app/models/kanji.rb
require 'rasem'

class Kanji < ActiveRecord::Base
    def to_param
        character
    end

    serialize :stroke_data, Array
    has_many :meanings, dependent: :destroy
    has_many :onyomis, dependent: :destroy
    has_many :kunyomis, dependent: :destroy
    has_many :nanoris, dependent: :destroy
end

app/models/kunyomi.rb
class Kunyomi < ActiveRecord::Base
    belongs_to :kanji
end

app/models/meaning.rb
class Meaning < ActiveRecord::Base
    belongs_to :kanji
end

app/models/nanori.rb
class Nanori < ActiveRecord::Base
    belongs_to :kanji
end

app/models/onyomi.rb
class Onyomi < ActiveRecord::Base
    belongs_to :kanji
end

app/models/photo.rb
class Photo < ActiveRecord::Base
    self.per_page = 6

    has_attached_file :file, :styles => { :small => "250x250#", :medium => "500x500#", :large => "1000x1000#" }

    validates_attachment_presence :file 
    validates_attachment_size :file, 
        :less_than => 10.megabytes
    validates_attachment_content_type :file,
        :content_type => ['image/jpeg', 'image/png']

    before_create :randomize_file_name

    belongs_to :user

    private

    def randomize_file_name
        extension = File.extname(file_file_name).downcase
        self.file.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
    end

end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
    self.per_page = 10

    validates_presence_of :english, :on => :create 
    validates_presence_of :japanese, :on => :create 
    validates_presence_of :japanese_raw, :on => :create 
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    
    has_many :photos

    has_many :user_words
    has_many :words, :through => :user_words

    before_validation :downcase_email
    
    validates_presence_of :password, :on => :create
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates_uniqueness_of :email

    private
    def downcase_email
        self.email = self.email.downcase if self.email.present?
    end
end

app/models/user_word.rb
class UserWord < ActiveRecord::Base
    belongs_to :user
    belongs_to :word
end

app/models/word.rb
# encoding: utf-8

class Word < ActiveRecord::Base
    def to_param
        @words = Word.where(:kanji => kanji)

        if @words.count() == 1
            kanji
        else
            "#{kanji}-#{id}"
        end
    end
    
    self.per_page = 10
    
    has_many :definitions

    has_many :user_words
    has_many :users, :through => :user_words

    validates_presence_of :kanji, :on => :create

    def self.search(q)
        result = joins(:definitions)

        q.strip!
        if q.length > 0
            q.split(/[ 　]+/).each do |w|
                if w.include? "*"
                    patt = w.gsub "*", "%"
                else
                    patt = "%#{w}%"
                end
            
                if w.ascii_only?
                    result = result.where("LOWER(definitions.text) LIKE LOWER(?)", "%#{w}%")
                else
                    result = result.where("kanji LIKE ? or kana LIKE ?", patt, patt)
                end
            end
        end

        result.group("words.id").order("common DESC, length(kanji), kana")
    end
end

app/helpers/japanese_helper.rb
# encoding: utf-8

module JapaneseHelper
    def hiragana_char?(c)
        "\u{3041}" <= c and c <= "\u{3094}"
    end

    def katakana_char?(c)
        "\u{30a1}" <= c and c <= "\u{30fb}"
    end

    def kana_symbol?(c)
        c == "\u{309e}" or 
        c == "\u{309b}" or
        c == "\u{309c}" or
        c == "\u{30fc}" or
        c == "\u{ff70}"
    end

    def hiragana?(str)
        str.scan(/./).all? do |c|
            hiragana_char? c or kana_symbol? c
        end
    end

    def katakana?(str)
        str.scan(/./).all? do |c|
            katakana_char? c or kana_symbol? c
        end
    end

    def kana?(str)
        str.scan(/./).all? do |c|
            hiragana_char? c or katakana_char? c or kana_symbol? c
        end       
    end

    def katakana_to_hiragana(str)
        str.unpack("U*").map { |c|
            if c >= 0x30a1 and c <= 0x30fb
                c-96
            else
                c
            end
        }.pack("U*")
    end

    def hiragana_to_katakana(str)
        str.unpack("U*").map { |c|
            if c >= 0x3041 and c <= 0x3094
                c+96
            else
                c
            end
        }.pack("U*")
    end
end

app/helpers/kanji_helper.rb
module KanjiHelper
end

app/helpers/kanjis_helper.rb
module KanjisHelper
end

app/helpers/nakama_helper.rb
module NakamaHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_words_helper.rb
module UserWordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
# encoding: UTF-8

module WordsHelper
    def verb_forms(word)
        forms = [word]

        if word =~ /[うるつすぐくぬむ]$/
            case word[-1]
            when 'う'
                forms << word.sub(/う$/, "い")
                forms << word.sub(/う$/, "って")
                forms << word.sub(/う$/, "った")
                forms << word.sub(/う$/, "わ")
                forms << word.sub(/う$/, "お")
                forms << word.sub(/う$/, "え")
            when 'る'
                forms << word.sub(/る$/, "り")
                forms << word.sub(/る$/, "ら")
                forms << word.sub(/る$/, "って")
                forms << word.sub(/る$/, "た")
                forms << word.sub(/る$/, "て")
                forms << word.sub(/る$/, "ろ")
                forms << word.sub(/る$/, "よ")
                forms << word.sub(/る$/, "れ")
                forms << word.sub(/る$/, "")
            when 'つ'
                forms << word.sub(/つ$/, "ち")
                forms << word.sub(/つ$/, "た")
                forms << word.sub(/つ$/, "った")
                forms << word.sub(/つ$/, "って")
                forms << word.sub(/つ$/, "と")
                forms << word.sub(/つ$/, "て")
            when 'す'
                forms << word.sub(/す$/, "して")
                forms << word.sub(/す$/, "さ")
                forms << word.sub(/す$/, "した")
                forms << word.sub(/す$/, "し")
                forms << word.sub(/す$/, "そ")
                forms << word.sub(/す$/, "せ")
            when 'ぐ'
                forms << word.sub(/ぐ$/, "いだ")
                forms << word.sub(/ぐ$/, "いで")
                forms << word.sub(/ぐ$/, "ぎ")
                forms << word.sub(/ぐ$/, "が")
                forms << word.sub(/ぐ$/, "ご")
                forms << word.sub(/ぐ$/, "げ")
            when 'く'
                forms << word.sub(/く$/, "いた")
                forms << word.sub(/く$/, "いて")
                forms << word.sub(/く$/, "き")
                forms << word.sub(/く$/, "か")
                forms << word.sub(/く$/, "こ")
                forms << word.sub(/く$/, "け")
            when 'ぬ'
                forms << word.sub(/ぬ$/, "んだ")
                forms << word.sub(/ぬ$/, "んで")
                forms << word.sub(/ぬ$/, "に")
                forms << word.sub(/ぬ$/, "な")
                forms << word.sub(/ぬ$/, "の")
                forms << word.sub(/ぬ$/, "ね")
            when 'む'
                forms << word.sub(/む$/, "んだ")
                forms << word.sub(/む$/, "んで")
                forms << word.sub(/む$/, "み")
                forms << word.sub(/む$/, "ま")
                forms << word.sub(/む$/, "も")
                forms << word.sub(/む$/, "め")
            end

            
        end

        return forms
    end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= msg %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default role="navigation">
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <%= link_to root_path, :class => "navbar-brand" do %>
        <%= image_tag "logo.png" %><%= title %>
    <% end %>
</div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">   
        <li class="dropdown"> 
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-book"></i> Dictionary <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <%= navbar_link_to "Search", "search", dictionary_path %>
            <%= navbar_link_to "Glossary", "font", glossary_path %>
        </ul>
        </li>
        <% if current_user %>
            <%= navbar_link_to "My images", "picture-o", myimages_path %>
            <%= navbar_link_to "My words", "list", mywords_path %>
        <% end %>
        <%= navbar_link_to "About", "question", about_path %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <%= navbar_link_to "Sign out", "sign-out", logout_path %>
        <% else %>
            <%= navbar_link_to "Sign in", "sign-in", login_path %>
        <% end %>
    </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> 
        <meta name="description" content="<%= title %> - <%= content_for?(:description) ? yield(:description) : "Japanese dictionary with OCR feature, example sentences and kanji search." %>">
        <meta name="keywords" content="japanese,dictionary,kanji,ocr,language,english,sentences">
        <meta name="author" content="Andreas Argelius">
        <title><%= title %> - <%= content_for?(:title) ? yield(:title) : "No title" %></title>
        <%= csrf_meta_tags %>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
        <![endif]-->

        <link href='http://fonts.googleapis.com/css?family=Alegreya' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>

        <%= javascript_include_tag "application" %>
        <%= stylesheet_link_tag "application", :media => "all" %>
    </head>
    <body>
        <div class="container">
            <%= render "layouts/navbar" %>
            <div class="row">
                <div class="col-xs-12">
                    <%= render "layouts/messages" %>
                    <%= yield %>
                </div>
            </div><!--/row-->
        </div> <!-- /container -->
        <div class="loading-modal"></div>
    </body>
</html>